fix running some of the tests on Go 1.13
Go 1.13 has GO111MODULE=on as a default, so some of the tests now
started failing. For example, config_projectroot.txt ran some 'go list'
commands with no go.mod file underneath, meaning that 1.12 was falling
back to GOPATH mode.

First, make those errors more obvious; before they used to be just:

	error: lstat : no such file or directory

This was because 'go list -m -f={{.Dir}}' would return an empty string,
so we'd try to filepath.Walk an empty path.

Second, add go.mod files where appropriate in the tests. Not having
these go.mod files was likely an oversight, as they are needed to
properly load packages in module mode.

Third, modify the 'gomod' test case, as it's not possible to load a
module's packages from another module via relative paths.